-- Production hardening: ownership, atomic quota + graph creation, RAG and billing state.
create extension if not exists vector with schema extensions;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profile(id) on delete cascade,
  study_bot_id bigint not null references public.study_bots(id) on delete cascade,
  document_id bigint references public.study_bot_documents(id) on delete cascade,
  document_name text not null check (char_length(document_name) between 1 and 255),
  content text not null check (char_length(content) > 0),
  chunk_index integer not null check (chunk_index >= 0),
  mime_type text,
  source_type text not null default 'text',
  source_locator text,
  embedding extensions.vector(384),
  fts tsvector generated always as (to_tsvector('english', coalesce(content, ''))) stored,
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);
-- Brownfield: earlier migration created document_chunks without source_locator.
alter table public.document_chunks add column if not exists source_locator text;
alter table public.document_chunks enable row level security;
drop policy if exists document_chunks_select_own on public.document_chunks;
create policy document_chunks_select_own on public.document_chunks for select to authenticated using (profile_id = (select auth.uid()));
drop policy if exists document_chunks_insert_own on public.document_chunks;
create policy document_chunks_insert_own on public.document_chunks for insert to authenticated with check (profile_id = (select auth.uid()) and exists (select 1 from public.study_bots b where b.id = study_bot_id and b.profile_id = (select auth.uid())));
drop policy if exists document_chunks_delete_own on public.document_chunks;
create policy document_chunks_delete_own on public.document_chunks for delete to authenticated using (profile_id = (select auth.uid()));
create index if not exists document_chunks_owner_bot_idx on public.document_chunks(profile_id, study_bot_id, chunk_index);
create index if not exists document_chunks_fts_idx on public.document_chunks using gin(fts);

create table if not exists public.billing_events (
  stripe_event_id text primary key,
  event_type text not null,
  created_at timestamptz not null,
  processed_at timestamptz not null default now(),
  payload jsonb not null
);
alter table public.billing_events enable row level security;
revoke all on public.billing_events from anon, authenticated;

-- User-facing clients must never be able to manufacture entitlements or quotas.
create or replace function public.protect_profile_entitlements()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if auth.uid() is not null and auth.uid() = old.id and
     (new.is_subscribed is distinct from old.is_subscribed or
      new.sets_remaining is distinct from old.sets_remaining or
      new.chats_remaining is distinct from old.chats_remaining or
      new.sets_refresh_at is distinct from old.sets_refresh_at) then
    raise exception 'Entitlements may only be changed by the billing service';
  end if;
  return new;
end;
$$;
drop trigger if exists profile_entitlement_guard on public.profile;
create trigger profile_entitlement_guard before update on public.profile for each row execute function public.protect_profile_entitlements();

create or replace function public.create_set_graph_with_quota(graph_data jsonb)
returns bigint language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid(); set_id bigint; lesson jsonb; quiz jsonb; question jsonb; lesson_id bigint; quiz_id bigint; question_id bigint; i int; j int; k int; remaining int; refresh_at timestamptz; subscribed boolean;
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  if jsonb_typeof(graph_data->'lessons') <> 'array' or jsonb_typeof(graph_data->'quizzes') <> 'array' or jsonb_array_length(graph_data->'lessons') = 0 or jsonb_array_length(graph_data->'lessons') <> jsonb_array_length(graph_data->'quizzes') then raise exception 'Invalid learning set graph'; end if;
  select sets_remaining, sets_refresh_at, is_subscribed into remaining, refresh_at, subscribed from public.profile where id=uid for update;
  if not found then raise exception 'Profile not found'; end if;
  if refresh_at is null or refresh_at <= now() then
    remaining := case when subscribed then 5 else 1 end;
    refresh_at := date_trunc('day', now() at time zone 'utc') + interval '1 day';
  end if;
  if remaining <= 0 then raise exception 'QUOTA_EXHAUSTED'; end if;
  update public.profile set sets_remaining=remaining-1, sets_refresh_at=refresh_at where id=uid;
  insert into public.sets(profile_id,title,description,category) values(uid, left(coalesce(graph_data->>'title',''),200), coalesce(graph_data->>'description',''), coalesce(graph_data->>'category','Miscellaneous')) returning id into set_id;
  for i in 0..jsonb_array_length(graph_data->'lessons')-1 loop
    lesson := graph_data->'lessons'->i; quiz := graph_data->'quizzes'->i;
    insert into public.lessons(set_id,title,position) values(set_id, lesson->>'title', i) returning id into lesson_id;
    for j in 0..coalesce(jsonb_array_length(lesson->'paragraphs'),0)-1 loop insert into public.paragraphs(lesson_id,content,position) values(lesson_id, lesson->'paragraphs'->>j,j); end loop;
    insert into public.quizzes(lesson_id,title) values(lesson_id,quiz->>'title') returning id into quiz_id;
    for j in 0..coalesce(jsonb_array_length(quiz->'questions'),0)-1 loop
      question:=quiz->'questions'->j; insert into public.questions(quiz_id,question,answer,position) values(quiz_id,question->>'question',question->>'answer',j) returning id into question_id;
      for k in 0..coalesce(jsonb_array_length(question->'options'),0)-1 loop insert into public.options(question_id,option,position) values(question_id,question->'options'->>k,k); end loop;
    end loop;
  end loop;
  return set_id;
end;
$$;
revoke all on function public.create_set_graph_with_quota(jsonb) from public, anon;
grant execute on function public.create_set_graph_with_quota(jsonb) to authenticated;

-- Keep the app-compatible signature (filter_profile_id + match_threshold) from
-- 20260711043419. The alternate 3-arg form would break lib/ingest/retrieve.ts.
create or replace function public.match_document_chunks(
  query_embedding extensions.vector(384),
  filter_study_bot_id bigint,
  filter_profile_id uuid,
  match_count integer default 8,
  match_threshold float default 0.15
)
returns table(
  id bigint,
  document_name text,
  content text,
  chunk_index integer,
  similarity float
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    dc.id,
    dc.document_name,
    dc.content,
    dc.chunk_index,
    (1 - (dc.embedding <=> query_embedding))::float as similarity
  from public.document_chunks dc
  where dc.study_bot_id = filter_study_bot_id
    and dc.profile_id = filter_profile_id
    and dc.embedding is not null
    and 1 - (dc.embedding <=> query_embedding) > match_threshold
  order by dc.embedding <=> query_embedding asc
  limit least(match_count, 50);
$$;
grant execute on function public.match_document_chunks(extensions.vector, bigint, uuid, integer, float)
  to authenticated, service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('study-documents','study-documents',false,41943040,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','text/plain','text/markdown','text/csv','image/png','image/jpeg'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists study_documents_select_own on storage.objects;
create policy study_documents_select_own on storage.objects for select to authenticated using(bucket_id='study-documents' and (storage.foldername(name))[1]=(select auth.uid()::text));
drop policy if exists study_documents_insert_own on storage.objects;
create policy study_documents_insert_own on storage.objects for insert to authenticated with check(bucket_id='study-documents' and (storage.foldername(name))[1]=(select auth.uid()::text));
drop policy if exists study_documents_delete_own on storage.objects;
create policy study_documents_delete_own on storage.objects for delete to authenticated using(bucket_id='study-documents' and (storage.foldername(name))[1]=(select auth.uid()::text));
